[package]
name = "cargo-concordium"
version = "2.7.0"
authors = ["Concordium <developers@concordium.com>"]
edition = "2018"
license-file = "../LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
structopt = "0.3"
hex = "0.4"
base64= "0.21"
serde = "1.0"
serde_json="1.0"
anyhow = "1.0"
ansi_term = "0.12"
ptree = "0.4"
strsim = "0.10"
which = "4.3"
rand = { version = "=0.7", features = ["small_rng"] }
cargo_metadata = "0.15"

[features]

[dependencies.concordium-wasm]
path = "../concordium-base/smart-contracts/wasm-transform"
version = "1.0"

[dependencies.concordium-smart-contract-engine]
version = "1.0"
path = "../concordium-base/smart-contracts/wasm-chain-integration/"
features = ["display-state"]

[dev-dependencies]
criterion = "0.3"

[dependencies.concordium-contracts-common]
version = "5.3.1"
path = "../concordium-base/concordium-contracts-common/concordium-contracts-common"
features = ["derive-serde", "std"]
