name: Build and test

# This job runs rustfmt and clippy linting,
# cargo check on cargo-concordium,

on:
  push:
    branches: main

  pull_request:
    branches: main

  workflow_dispatch: # allows manual trigger

env:
  # from concordium/rustfmt:0.17
  RUST_FMT: nightly-2021-06-09-x86_64-unknown-linux-gnu
  RUST_CLIPPY: 1.53
  TARGET: wasm32-unknown-unknown

jobs:
  "lint_fmt":
    name: ${{ matrix.build-dir }} lint:fmt
    # Don't run on draft pull requests
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-dir:
          - 'cargo-concordium'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_FMT }}
          override: true
          components: rustfmt
      - name: Format
        working-directory: ${{ matrix.build-dir }}
        run: |
          cargo fmt -- --color=always --check

  "lint_clippy":
    name: ${{ matrix.build-dir }} lint:clippy
    # Don't run on draft pull requests
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-dir:
          - 'cargo-concordium'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_CLIPPY }}
          override: true
          target: ${{ env.TARGET }}
          components: clippy
      - name: Clippy
        working-directory: ${{ matrix.build-dir }}
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          cargo clippy --color=always --tests --benches -- -Dclippy::all

  "cargo-concordium_cargo_build-bench":
    name: cargo-concordium cargo:build-bench
    runs-on: ubuntu-latest
    needs:
      - lint_clippy
      - lint_fmt
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_CLIPPY }}
          override: true
          target: ${{ env.TARGET }}
          components: clippy
      - name: Cargo check
        working-directory: cargo-concordium
        run: cargo check --benches --tests

  "cargo_test":
    name: ${{ matrix.build-dir }} cargo:test
    runs-on: ubuntu-latest
    needs:
      - cargo-concordium_cargo_build-bench
    strategy:
      matrix:
        build-dir:
          - 'cargo-concordium'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_CLIPPY }}
          override: true
      - name: Test
        working-directory: ${{ matrix.build-dir }}
        run: cargo test


