name: "cargo-concordium: Build and test"

# This job runs rustfmt and clippy linting,
# cargo check on cargo-concordium,
# and then it runs cargo test and ./target/debug/wasm-test

on:
  push:
    branches: main

  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - 'cargo-concordium/**/*.rs'
      - 'cargo-concordium/**/*.toml'
      - 'rustfmt.toml'
      - 'Cargo.toml'
      - 'rust-toolchain.toml'
      - 'concordium-base'

  workflow_dispatch: # allows manual trigger

jobs:
  "lint_fmt":
    name: lint:fmt
    # Don't run on draft pull requests
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Format
        run: |
          rustup component add rustfmt
          cargo fmt -- --color=always --check

  "lint_clippy_binaries":
    name: lint:clippy
    # Don't run on draft pull requests
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Clippy
        run: |
          rustup component add clippy
          cargo clippy --color=always --all-targets --all-features --locked -- -D warnings

  "cargo_test":
    name: cargo:test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Test
        run: cargo test --all-features

  rustdoc:
    name: cargo:doc
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Docs
        run: |
          rustup component add rust-docs
          RUSTDOCFLAGS="-D warnings" cargo doc --no-deps --all-features