name: Create and publish a Docker image for verifiable-sc.

on:
  workflow_dispatch: # allows manual trigger

  push:
    tags:
      - 'verifiable-sc/*.*.*'

env:
  REGISTRY: docker.io
  SERVICE_NAME: 'verifiable-sc'
  SOURCE_IMAGE_TAG: 'rust:1.75.0'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: testnet-deployments
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      # Uses the `docker/login-action` action to log in to the Container registry.
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract version from git tag
        id: meta
        env:
            TAG: ${{ github.ref_name }}
        run: |
            SERVICE_TAG=${TAG##${{ env.SERVICE_NAME }}/}
            echo "tag=${{ env.REGISTRY }}concordium/${{ env.SERVICE_NAME }}-${TAG_VERSION}" >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ./reproducible/build.Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tag }}
          build-args: |
            source_image=${{ env.SOURCE_IMAGE_TAG }}
